global:
  resolve_timeout: 10s

route:
  group_by: ['alertname']
  group_wait: 3s
  receiver: 'telegram_bot'

receivers:
- name: 'telegram_bot'
  telegram_configs:
  - bot_token: '6093419321:AAHDqhFKlurTicYY1RhaZ_cOtsrOALT9_iU'
    api_url: 'https://api.telegram.org'
    chat_id: 911073420
    parse_mode: 'HTML'